import { derived, writable } from "svelte/store";

export type Lang = "en" | "fr";

const dict = {
  en: {
    // nav
    nav_overview: "Overview", nav_portfolio: "Portfolio", nav_performance: "Performance",
    nav_stocks: "Stocks", nav_tax: "Tax", nav_settings: "Settings",
    // topbar
    prices_sample: "Sample data", prices_lasttx: "Prices: last transaction",
    prices_manual: "Prices: manual", prices_online: "Prices: online",
    refresh: "Refresh", refreshing: "Refreshing…", refresh_fail: "Refresh failed — is the proxy running?",
    theme: "Theme", import: "Import",
    print: "Print", print_generated: "Generated by TradeRepublicBoard",
    export: "Export", xlsx_summary: "Summary",
    // hero + kpis
    hero_label: "Portfolio value", all_time: "all time",
    kpi_contrib: "Contributions", kpi_contrib_sub: "your money in",
    kpi_saveback: "Saveback received", kpi_saveback_sub: "“free”, reinvested",
    kpi_cost: "Total cost", kpi_cost_sub: "buys + saveback",
    kpi_fees: "Fees", kpi_fees_sub: "on your orders",
    kpi_perf: "Market perf",
    kpi_savebackworth: "Saveback worth", kpi_savebackworth_sub: "value of the “free” shares",
    // cards
    c_value: "Value over time", c_value_sub: "Portfolio value vs invested cost — the gap is your unrealised gain.",
    c_alloc: "Allocation", c_movers: "Movers", c_movers_sub: "by unrealised gain/loss",
    c_holdings: "Holdings", legend_value: "Value", legend_cost: "Cost",
    holdings_count: "holdings", stock_picking: "Stock picking", realised: "realised",
    // table headers
    th_name: "Name", th_shares: "Shares", th_cost: "Cost", th_value: "Value",
    th_gainloss: "Gain/Loss", total: "Total",
    th_buys: "Buys", th_saveback: "Saveback", th_totalcost: "Total cost", th_price: "Price",
    sec_etfs: "ETFs",
    sec_byyear: "Per-year detail", by_line: "By ETF / stock",
    th_sharesacq: "Shares acquired", th_valuetoday: "Value today",
    // portfolio drilldown
    pf_click_hint: "Click a holding to follow it over time.",
    byyear_sub: "Monthly recap — expand a month to see each instrument.",
    cohort_hint: "Gain on the shares bought in this period, valued at today's price.",
    back_pf: "‹ Portfolio", badge_stock: "Stock",
    a_invested: "Invested", a_hist_year: "History by year",
    a_nochart: "Not enough history yet to chart this position.",
    a_notfound: "This asset isn't in the current data.",
    a_follow_sub: "Your investment in this line, year by year and month by month.",
    // performance page
    perf_break: "Performance breakdown", perf_basis: "Basis", perf_measures: "What it measures",
    perf_tr: "Market (TR method)", perf_tr_m: "Return on all invested money",
    perf_sav: "Saveback contribution", perf_sav_m: "Today's value of the “free” shares",
    perf_monthly: "Month by month", th_month: "Month", th_gain: "Gain",
    // tax page
    tax_title: "Tax summary", tax_sub: "Ordinary securities account — flat tax 30% unless you opt for the scale.",
    th_year: "Year", tax_interest: "Cash interest", tax_realised: "Realised gains",
    tax_base: "Taxable base", tax_estimate: "Est. tax 30%", tax_contrib: "Contributions",
    tax_note1: "Cash interest is taxable in the year received.",
    tax_note2: "Accumulating ETFs are taxed only on a sale (realised gain).",
    tax_note3: "Indicative estimate — not tax advice.",
    // stocks page
    st_title: "Stock picking", st_sub: "Single stocks — weighted-average cost, realised & unrealised P/L.",
    th_company: "Company", th_avgcost: "Avg cost", th_unrealised: "Unrealised", th_realised: "Realised",
    st_empty: "No single-stock trades in this export.",
    // portfolio page
    pf_sub: "Everything you hold, by value.",
    // settings page
    set_sub: "Everything here is computed on your device — no account, no network.",
    set_appearance: "Appearance", set_language: "Language",
    set_theme_light: "Light", set_theme_dark: "Dark",
    set_prices: "Current prices", set_prices_sub: "Markets are fetched by no one — set the latest price per holding by hand. Applied instantly, on your device only.",
    set_price_ph: "last tx", set_price_reset: "Reset to last transaction",
    set_price_manual_on: "Manual prices are active.", set_price_fallback_on: "Using last-transaction prices.",
    set_online: "Online prices",
    set_online_sub: "Optional. Fetch current prices by ISIN from a proxy you run — only the ISIN leaves your browser, never your holdings. Leave empty to stay fully offline.",
    set_proxy_url: "Proxy URL", set_refresh_now: "Refresh prices now",
    set_data: "Data & privacy",
    set_data_sub: "Your CSV and prices stay in this tab’s session and vanish when you close it.",
    set_status_sample: "Showing sample data.", set_status_imported: "Showing your imported data.",
    set_clear: "Clear data", set_clear_sub: "Remove the CSV and prices from this browser now.",
    // empty state
    e_title: "Your portfolio, privately.",
    e_sub: "Your Trade Republic CSV is read entirely in your browser — it never leaves your device.",
    e_drop: "Drop your Trade Republic CSV, or click to browse",
    e_local: "Processed locally · nothing uploaded", e_try: "Try with sample data →",
    mock_note: "Data stays in your browser. Prices default to the last transaction price until you refresh.",
  },
  fr: {
    nav_overview: "Vue d'ensemble", nav_portfolio: "Portefeuille", nav_performance: "Performance",
    nav_stocks: "Actions", nav_tax: "Fiscalité", nav_settings: "Réglages",
    prices_sample: "Données d'exemple", prices_lasttx: "Cours : dernière transaction",
    prices_manual: "Cours : manuels", prices_online: "Cours : en ligne",
    refresh: "Actualiser", refreshing: "Actualisation…", refresh_fail: "Échec — le proxy tourne-t-il ?",
    theme: "Thème", import: "Importer",
    print: "Imprimer", print_generated: "Généré par TradeRepublicBoard",
    export: "Exporter", xlsx_summary: "Résumé",
    hero_label: "Valeur du portefeuille", all_time: "depuis le début",
    kpi_contrib: "Versements", kpi_contrib_sub: "ton argent investi",
    kpi_saveback: "Saveback reçu", kpi_saveback_sub: "« offert », réinvesti",
    kpi_cost: "Coût total", kpi_cost_sub: "achats + saveback",
    kpi_fees: "Frais", kpi_fees_sub: "sur tes ordres",
    kpi_perf: "Perf marché",
    kpi_savebackworth: "Valeur du saveback", kpi_savebackworth_sub: "valeur des parts « offertes »",
    c_value: "Valeur dans le temps", c_value_sub: "Valeur du portefeuille vs coût investi — l'écart est ta plus-value latente.",
    c_alloc: "Répartition", c_movers: "Mouvements", c_movers_sub: "par plus/moins-value latente",
    c_holdings: "Positions", legend_value: "Valeur", legend_cost: "Coût",
    holdings_count: "positions", stock_picking: "Stock picking", realised: "réalisée",
    th_name: "Nom", th_shares: "Parts", th_cost: "Coût", th_value: "Valeur",
    th_gainloss: "+/- value", total: "Total",
    th_buys: "Achats", th_saveback: "Saveback", th_totalcost: "Coût total", th_price: "Cours",
    sec_etfs: "ETF",
    sec_byyear: "Détail par année", by_line: "Par ETF / action",
    th_sharesacq: "Parts acquises", th_valuetoday: "Valeur auj.",
    pf_click_hint: "Clique une ligne pour la suivre dans le temps.",
    byyear_sub: "Récap mensuel — déplie un mois pour voir chaque instrument.",
    cohort_hint: "Plus-value des parts achetées sur la période, au cours du jour.",
    back_pf: "‹ Portefeuille", badge_stock: "Action",
    a_invested: "Investi", a_hist_year: "Historique par année",
    a_nochart: "Pas encore assez d'historique pour tracer cette position.",
    a_notfound: "Cet actif n'est pas dans les données actuelles.",
    a_follow_sub: "Ton investissement sur cette ligne, année par année et mois par mois.",
    perf_break: "Décomposition de la performance", perf_basis: "Base", perf_measures: "Ce que ça mesure",
    perf_tr: "Marché (méthode TR)", perf_tr_m: "Rendement de tout l'argent investi",
    perf_sav: "Apport du saveback", perf_sav_m: "Valeur actuelle des parts « offertes »",
    perf_monthly: "Mois par mois", th_month: "Mois", th_gain: "+/- value",
    tax_title: "Récapitulatif fiscal", tax_sub: "Compte-titres ordinaire — PFU 30 % sauf option barème.",
    th_year: "Année", tax_interest: "Intérêts espèces", tax_realised: "Plus-values réalisées",
    tax_base: "Base imposable", tax_estimate: "Est. prélèvement 30 %", tax_contrib: "Versements",
    tax_note1: "Les intérêts espèces sont imposables l'année de perception.",
    tax_note2: "Les ETF capitalisants ne sont imposés qu'à la revente (plus-value réalisée).",
    tax_note3: "Estimation indicative — pas un conseil fiscal.",
    st_title: "Stock picking", st_sub: "Actions individuelles — prix moyen pondéré, +/- values réalisées & latentes.",
    th_company: "Société", th_avgcost: "PMP", th_unrealised: "Latente", th_realised: "Réalisée",
    st_empty: "Aucune opération sur action individuelle dans cet export.",
    pf_sub: "Tout ce que tu détiens, par valeur.",
    set_sub: "Tout est calculé sur ton appareil — sans compte, sans réseau.",
    set_appearance: "Apparence", set_language: "Langue",
    set_theme_light: "Clair", set_theme_dark: "Sombre",
    set_prices: "Cours actuels", set_prices_sub: "Aucun cours n'est récupéré en ligne — renseigne le dernier cours par ligne à la main. Appliqué aussitôt, uniquement sur ton appareil.",
    set_price_ph: "dern. tx", set_price_reset: "Revenir à la dernière transaction",
    set_price_manual_on: "Cours manuels actifs.", set_price_fallback_on: "Cours de la dernière transaction.",
    set_online: "Cours en ligne",
    set_online_sub: "Optionnel. Récupère les cours par ISIN via un proxy que tu héberges — seul l'ISIN quitte ton navigateur, jamais tes positions. Laisse vide pour rester 100 % hors-ligne.",
    set_proxy_url: "URL du proxy", set_refresh_now: "Actualiser les cours",
    set_data: "Données & confidentialité",
    set_data_sub: "Ton CSV et tes cours restent dans la session de cet onglet et disparaissent à sa fermeture.",
    set_status_sample: "Données d'exemple affichées.", set_status_imported: "Tes données importées sont affichées.",
    set_clear: "Effacer les données", set_clear_sub: "Retire le CSV et les cours de ce navigateur maintenant.",
    e_title: "Ton portefeuille, en privé.",
    e_sub: "Ton CSV Trade Republic est lu entièrement dans ton navigateur — il ne quitte jamais ton appareil.",
    e_drop: "Dépose ton CSV Trade Republic, ou clique pour parcourir",
    e_local: "Traité en local · rien n'est envoyé", e_try: "Essayer avec des données d'exemple →",
    mock_note: "Tes données restent dans le navigateur. Les cours affichés sont ceux de la dernière transaction jusqu'à actualisation.",
  },
} as const;

export type Key = keyof (typeof dict)["en"];

function initialLang(): Lang {
  if (typeof localStorage !== "undefined") {
    const v = localStorage.getItem("lang");
    if (v === "fr" || v === "en") return v;
  }
  return "en";
}

export const lang = writable<Lang>(initialLang());

export function setLang(l: Lang): void {
  lang.set(l);
  if (typeof localStorage !== "undefined") localStorage.setItem("lang", l);
}

/** Reactive translator: `$t('key')`. */
export const t = derived(lang, ($l) => (key: Key): string => dict[$l][key] ?? key);
